[package]
name = "scan_mvcf"
version = "0.1.0"
authors = ["PThorpe92 <preston@unlockedlabs.org>"]
license = "MIT"
edition = "2021"

[dependencies]
serde_json = { version = "1.0.108", features = ["std"] }
serde = { version = "1.0.190", features = ["derive"] }
rusqlite = "0.29.0"
dirs = "5.0.1"
hidapi = "2.4.1"
once_cell = "1.18.0"
chrono = "0.4.31"
actix = "0.13.0"
actix-web = { version = "4.4.0", features = ["http2", "macros"] }
r2d2_sqlite = "0.22.0"
r2d2 = "0.8.10"
env_logger = "0.10.0"
log = "0.4.20"
futures-util = "0.3.29"
serde_with = "3.4.0"
reqwest = "0.11.22"
actix-cors = "0.6.4"
