services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: mvcf-scanner
      POSTGRES_USER: mvcf
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
