//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6
use crate::prelude::OrmSerializable;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

impl OrmSerializable for Model {}

#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "locations")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub level: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::timestamps::Entity")]
    Timestamps,
}

impl Related<super::timestamps::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Timestamps.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
