//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::locations::Entity as Locations;
pub use super::residents::Entity as Residents;
pub use super::timestamps::Entity as Timestamps;

pub trait OrmSerializable {}
impl OrmSerializable for Locations {}
impl OrmSerializable for Residents {}
impl OrmSerializable for Timestamps {}
impl OrmSerializable for String {}
